/** Self-contained daemon client: no third-party scripts, telemetry, or credential persistence. */
export const webClient = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CodeSplash</title><style>
:root{color-scheme:dark;font:15px/1.5 system-ui;background:#101318;color:#e3e8ed}*{box-sizing:border-box}body{margin:0}header{position:sticky;top:0;background:#101318;z-index:1;display:flex;gap:16px;align-items:center;padding:18px 24px;border-bottom:1px solid #303640}header b{font-size:22px;color:#93e2db}main{display:grid;grid-template-columns:260px 1fr;min-height:90vh}aside{padding:20px;border-right:1px solid #303640}section{padding:24px;max-width:1000px;width:100%;margin:auto}input,textarea,select,button{font:inherit;border:1px solid #45505b;border-radius:6px;padding:9px;background:#1b2128;color:inherit}button{cursor:pointer}button:hover{background:#303b44}button:disabled{opacity:.4;cursor:default}input,textarea{width:100%}textarea{min-height:90px;resize:vertical}label{display:block;margin:12px 0 5px}#messages{height:55vh;overflow:auto;border-bottom:1px solid #303640;margin-bottom:16px}article{padding:12px 0;white-space:pre-wrap;overflow-wrap:anywhere}article small{color:#93e2db;display:block}#notice{color:#ffc68a;white-space:pre-wrap}#requests{padding:10px;background:#252b32}#requests:empty{display:none}.row{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.muted{color:#a4afba}.thread{display:block;margin:6px 0;width:100%;text-align:left}#login{max-width:450px;margin:15vh auto}#workspace{display:none}@media(max-width:650px){main{display:block}aside{border:0}#messages{height:45vh}}
</style></head><body><header><b>CodeSplash</b><span class="muted">Shared session workspace</span><span id="status"></span></header><div id="login"><h1>Connect to your daemon</h1><p>Enter the local daemon token or a one-time pairing code.</p><form id="auth"><label for="token">Token or pairing code</label><input id="token" type="password" autocomplete="off" required><div class="row"><button>Connect</button></div></form><p id="authError"></p></div><main id="workspace"><aside><h2>Sessions</h2><button id="refresh">Refresh</button><div id="threads"></div><label for="cwd">Workspace directory</label><input id="cwd" placeholder="/path/to/project"><button id="create">New session</button><p class="muted">Workspace roots and permissions are controlled by the daemon.</p></aside><section><h1 id="title">Choose a session</h1><div class="row"><select id="mode" aria-label="Access mode"><option value="reader">Read only</option><option value="shared">Shared writer</option><option value="exclusive">Exclusive writer</option></select><button id="acquire">Apply access</button><button id="steal">Take over writer</button><button id="interrupt">Interrupt</button><button id="share">Share</button><button id="unshare" disabled>Revoke last share</button></div><p id="notice" role="status"></p><div id="messages" aria-live="polite"></div><div id="requests"></div><form id="prompt"><label for="text">Message</label><textarea id="text" placeholder="Ask CodeSplash to work on this project"></textarea><div class="row"><button id="send">Send</button></div></form></section></main><script>
const $=id=>document.getElementById(id);let connection,thread,lease,epoch,seq=0,source;const events=new Map(),shares=new Map();
function note(e){$('notice').textContent=e instanceof Error?e.message:String(e)}
async function rpc(method,params={}){const r=await fetch('/rpc',{method:'POST',headers:{'Content-Type':'application/json',...(connection?{'x-codesplash-connection':connection}:{})},body:JSON.stringify({jsonrpc:'2.0',id:++seq,method,params})});if(!r.ok)throw Error('Daemon HTTP '+r.status);const v=await r.json();if(v.error)throw Error(v.error.message);return v.result}
function writable(){for(const id of ['send','interrupt','share'])$(id).disabled=!lease;$('unshare').disabled=!lease||!shares.has(thread)}
function draw(){const box=$('messages');box.replaceChildren();const messages=new Map();for(const e of [...events.values()].sort((a,b)=>a.sequence-b.sequence)){const p=e.payload;if(e.kind==='user.message')messages.set('u'+p.id,{role:'You',text:p.text});if(e.kind==='message.delta'){const m=messages.get(p.id)||{role:'CodeSplash',text:''};m.text+=p.text;messages.set(p.id,m)}if(e.kind==='message.completed'&&p.text)messages.set(p.id,{role:'CodeSplash',text:p.text});if(e.kind==='item.updated')messages.set('t'+p.id,{role:p.label+' · '+p.status,text:p.output||''})}for(const m of messages.values()){const a=document.createElement('article'),label=document.createElement('small');label.textContent=m.role;a.append(label,document.createTextNode(m.text));box.append(a)}box.scrollTop=box.scrollHeight}
function approvals(pending){$('requests').replaceChildren();for(const r of pending){const block=document.createElement('form'),title=document.createElement('p'),fields=[];block.onsubmit=e=>e.preventDefault();title.textContent=r.title+'\n'+(r.detail||'');block.append(title);for(const f of r.form?.fields||[]){const label=document.createElement('label'),input=document.createElement(f.choices?'select':'input');label.textContent=f.label;if(f.choices){for(const value of f.choices){const o=document.createElement('option');o.value=value;o.textContent=value;input.append(o)}}else input.type=f.type==='boolean'?'checkbox':f.type==='string'?'text':'number';input.required=f.required&&f.type!=='boolean';if(f.type==='integer')input.step='1';if(f.minimum!==undefined)input.min=f.minimum;if(f.maximum!==undefined)input.max=f.maximum;if(f.maxLength!==undefined)input.maxLength=f.maxLength;input.disabled=!lease;label.append(input);block.append(label);fields.push([f,input])}for(const choice of r.choices){const b=document.createElement('button');b.type='button';b.textContent=choice;b.disabled=!lease;b.onclick=()=>{const data=Object.create(null);if(r.form&&choice==='accept'){if(!block.reportValidity())return;for(const [f,input] of fields){if(!f.required&&f.type!=='boolean'&&input.value==='')continue;data[f.name]=f.type==='boolean'?input.checked:f.type==='string'?input.value:Number(input.value)}}rpc('request/respond',{threadId:thread,lease,requestId:r.id,choice,...(r.form&&choice==='accept'?{data}:{})}).then(snapshot).catch(note)};block.append(b)}$('requests').append(block)}}
async function snapshot(){if(!thread)return;const selected=thread,s=await rpc('thread/snapshot',{threadId:selected});if(selected!==thread)return;epoch=s.inputEpoch;$('title').textContent=s.cwd+' · '+s.threadId.slice(0,8);const newer=[...events.values()].filter(e=>e.sequence>s.cursor);events.clear();for(const e of [...s.events,...newer])events.set(e.sequence,e);draw();approvals(s.pending);writable()}
async function list(){const threads=await rpc('thread/list');$('threads').replaceChildren();for(const t of threads){const b=document.createElement('button');b.className='thread';b.textContent=t.id.slice(0,8)+' · '+t.cwd.split('/').pop();b.onclick=async()=>{try{if(lease)await rpc('lease/release',{threadId:thread,lease});thread=t.id;events.clear();lease=undefined;$('title').textContent=t.cwd;$('mode').value='reader';await snapshot()}catch(e){note(e)}};$('threads').append(b)}}
async function connected(){const v=await rpc('initialize',{version:1,client:'browser',experimental:['sharing','tui-control']});connection=v.connectionId;$('login').style.display='none';$('workspace').style.display='grid';source=new EventSource('/events?connection='+encodeURIComponent(connection));source.onmessage=ev=>{const n=JSON.parse(ev.data),p=n.params;if(n.method==='stream/ready'){snapshot().catch(note);return}if(p.threadId!==thread)return;if(n.method==='thread/event'){events.set(p.event.sequence,p.event);draw();if(p.event.kind.startsWith('request.'))snapshot().catch(note)}if(n.method==='lease/revoked'){lease=undefined;writable();note('Writer ownership changed')}if(n.method==='share/created'){shares.set(thread,p.shareId);writable();note(p.url||'Share created')}if(n.method==='tui/control'){if(p.action==='prompt')$('text').value=p.text;else note(p.text)}};source.onerror=()=>note('Stream reconnecting. Use Refresh if the daemon restarted.');await list();await selectLink();writable()}
async function selectLink(){const id=location.hash.slice(1);if(!connection||!id||id===thread)return;const items=await rpc('thread/list');if(!items.some(t=>t.id===id)){note('The linked session is not present in this daemon.');return}if(lease)await rpc('lease/release',{threadId:thread,lease});thread=id;lease=undefined;events.clear();$('mode').value='reader';await snapshot();note('Linked session selected · read only')}
window.addEventListener('hashchange',()=>selectLink().catch(note));
$('auth').onsubmit=async e=>{e.preventDefault();try{const r=await fetch('/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:$('token').value})});$('token').value='';if(!r.ok)throw Error('Authentication failed');await connected()}catch(e){$('authError').textContent=e.message}};
$('refresh').onclick=()=>list().then(snapshot).catch(note);$('create').onclick=async()=>{try{const r=await rpc('thread/create',{cwd:$('cwd').value});if(lease)await rpc('lease/release',{threadId:thread,lease});thread=r.threadId;events.clear();epoch=r.inputEpoch;lease=undefined;$('mode').value='reader';await list();await snapshot()}catch(e){note(e)}};
async function acquire(steal){if(!thread)return;try{if(lease){await rpc('lease/release',{threadId:thread,lease});lease=undefined}const mode=$('mode').value;if(mode!=='reader'){await rpc('thread/resume',{threadId:thread});lease=(await rpc('lease/acquire',{threadId:thread,mode,steal})).lease}await snapshot();note(mode==='reader'?'Read only':'Writer connected')}catch(e){note(e);writable()}}
$('acquire').onclick=()=>acquire(false);$('steal').onclick=()=>{if(confirm('Interrupt current work and revoke all writer leases?')){$('mode').value='exclusive';acquire(true)}};
$('prompt').onsubmit=async e=>{e.preventDefault();if(!lease)return;try{await rpc('turn/start',{threadId:thread,lease,text:$('text').value,submissionId:epoch+'.'+crypto.randomUUID()});$('text').value=''}catch(e){note(e)}};
$('interrupt').onclick=()=>rpc('turn/interrupt',{threadId:thread,lease}).catch(note);$('share').onclick=()=>{if(confirm('Create a redacted bearer link? Anyone with the link can read the export.'))rpc('share/create',{threadId:thread,lease}).then(v=>{shares.set(thread,v.shareId);writable();note(v.url)}).catch(note)};
$('unshare').onclick=()=>rpc('share/revoke',{threadId:thread,lease,shareId:shares.get(thread)}).then(()=>{shares.delete(thread);writable();note('Share revoked')}).catch(note);
connected().catch(()=>{});
setInterval(()=>{if(lease)rpc('lease/renew',{threadId:thread,lease}).catch(e=>{lease=undefined;writable();note(e)})},20000);
</script></body></html>`
