export const operationKinds = [
  "git.status",
  "git.diff",
  "git.add",
  "git.commit",
  "git.push",
  "git.pull",
  "git.fetch",
  "git.merge",
  "git.rebase",
  "git.cherry-pick",
  "git.checkout",
  "git.switch",
  "git.worktree",
  "git.clone",
  "git.pr-create",
  "index.ripgrep",
  "index.tree-sitter",
  "index.ast-grep",
  "index.zoekt",
  "index.sourcegraph",
  "index.semgrep",
] as const
export type OperationKind = (typeof operationKinds)[number]
